--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PresentKim/RealisticCompass-PMMP

branches:
- master

projects:
  RealisticCompass:
    path: ""
    icon: assets/icon/512x512.png
...
